version: '3'

services:
  api:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: etiquetador-login-lite
    ports:
      - 80:4000
      #80:4000
    command: npm start
    depends_on:
      - db
  db:
    image: mariadb:10.4.18
    restart: always
    volumes:
      - db_volume:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_USER: 'pablohoney'
      MYSQL_ROOT_PASSWORD: 'Pikachuy1-'
      MYSQL_USER: 'pablohoney'
      MYSQL_PASSWORD: 'Pikachuy1-'
      MYSQL_DATABASE: 'AustenRiggs'
    ports:
      - '3306:3306'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
      #80:8080

volumes: 
  db_volume:
